# Generated by Django 5.0.6 on 2024-05-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(max_length=255)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='notification_images/')),
            ],
        ),
    ]
