# Generated by Django 5.0.6 on 2024-05-24 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0002_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='State',
            new_name='state',
        ),
    ]
