# Generated by Django 5.0.6 on 2024-05-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0003_rename_state_person_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='banner_images/')),
            ],
        ),
    ]
