# Generated by Django 5.0.6 on 2024-05-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0004_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
