# Generated by Django 5.0.6 on 2024-05-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0005_alter_banner_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='redirect_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_url',
            field=models.ImageField(default=1, upload_to='banner_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
