# Generated by Django 5.0.6 on 2024-05-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0006_banner_redirect_url_alter_banner_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='sub_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
