# Generated by Django 5.0.6 on 2024-05-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0007_banner_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
