# Generated by Django 5.0.6 on 2024-05-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0008_alter_notification_id_alter_notification_sub_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
