# Generated by Django 5.0.6 on 2024-05-28 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0009_banner_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='linked_people',
            field=models.ManyToManyField(related_name='linked_people', to=settings.AUTH_USER_MODEL),
        ),
    ]
