# Generated by Django 5.0.6 on 2024-05-29 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0010_person_linked_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='linked_people',
        ),
    ]
