# Generated by Django 5.0.6 on 2024-05-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0012_alter_person_first_name_translateperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='guj_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='guj_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='surname',
            name='guj_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
