# Generated by Django 5.0.6 on 2024-05-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0013_city_guj_name_state_guj_name_surname_guj_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profiles/')),
            ],
        ),
        migrations.AlterField(
            model_name='translateperson',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='translateperson',
            name='first_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='translateperson',
            name='middle_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
