# Generated by Django 5.0.6 on 2024-05-30 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0014_profile_alter_translateperson_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
