# Generated by Django 5.0.6 on 2024-06-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0015_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('guj_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
