# Generated by Django 5.0.6 on 2024-06-03 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0016_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='out_of_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='out_of_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parivar.country'),
        ),
    ]
