# Generated by Django 5.0.6 on 2024-06-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0017_person_out_of_address_person_out_of_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='translateperson',
            name='out_of_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
