# Generated by Django 5.0.6 on 2024-06-03 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0018_translateperson_out_of_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='out_of_country',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='parivar.country'),
        ),
    ]
