# Generated by Django 5.0.6 on 2024-06-03 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0019_alter_person_out_of_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='out_of_country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parivar.country'),
        ),
    ]
