# Generated by Django 5.0.6 on 2024-06-06 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0021_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
