# Generated by Django 5.0.6 on 2024-06-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0022_delete_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
