# Generated by Django 5.0.6 on 2024-06-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0023_person_deleted_at_person_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='deleted_by',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
