# Generated by Django 5.0.6 on 2024-06-12 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0024_person_deleted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='deleted_at',
        ),
    ]
