# Generated by Django 5.0.6 on 2024-06-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parivar", "0025_remove_person_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="is_super_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person",
            name="password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
