# Generated by Django 5.0.6 on 2024-06-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parivar", "0026_person_is_super_admin_person_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="blood_group",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
