# Generated by Django 5.0.6 on 2024-06-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parivar", "0027_alter_person_blood_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="date_of_birth",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
