# Generated by Django 5.0.6 on 2024-07-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parivar", "0028_alter_person_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="out_of_mobile",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
