# Generated by Django 5.0.6 on 2024-07-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parivar", "0029_person_out_of_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="mobile_number2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
