# Generated by Django 5.0.6 on 2024-07-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parivar", "0030_alter_person_mobile_number2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="mobile_number2",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="out_of_mobile",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
