# Generated by Django 5.0.6 on 2024-07-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parivar", "0031_alter_person_mobile_number2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="is_same_as_father_address",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person",
            name="is_same_as_son_address",
            field=models.BooleanField(default=False),
        ),
    ]
