# Generated by Django 5.0.6 on 2024-07-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0032_person_is_same_as_father_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='child_flag',
            field=models.BooleanField(default=False),
        ),
    ]
