# Generated by Django 5.0.6 on 2024-07-19 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0033_person_child_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_visible',
        ),
        migrations.AddField(
            model_name='person',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='platform',
            field=models.CharField(blank=True, default='postman', max_length=30, null=True),
        ),
    ]
