# Generated by Django 5.0.6 on 2024-07-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0034_remove_person_is_visible_person_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surname',
            name='fix_order',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
