# Generated by Django 5.0.6 on 2024-08-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0035_surname_fix_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_title', models.CharField(max_length=200)),
                ('ads_setting', models.JSONField()),
                ('commit_no', models.CharField(default='0000', max_length=200)),
            ],
            options={
                'verbose_name': 'ads setting',
                'verbose_name_plural': 'ads setting',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='thumb_profile',
            field=models.ImageField(blank=True, null=True, upload_to='compress_img/'),
        ),
    ]
