# Generated by Django 5.0.6 on 2024-08-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0036_adssetting_person_thumb_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('first_name', 'middle_name', 'date_of_birth', 'surname', 'mobile_number1', 'mobile_number2')},
        ),
        migrations.AlterField(
            model_name='person',
            name='profile',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='thumb_profile',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='compress_img/'),
        ),
        migrations.AlterUniqueTogether(
            name='translateperson',
            unique_together={('person_id', 'first_name', 'middle_name', 'address', 'language')},
        ),
    ]
