# Generated by Django 5.0.6 on 2024-08-16 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0037_alter_person_unique_together_alter_person_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translateperson',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='parivar.person'),
        ),
    ]
