# Generated by Django 5.0.6 on 2024-08-16 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0038_alter_translateperson_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translateperson',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parivar.person'),
        ),
    ]
