# Generated by Django 5.0.6 on 2024-08-21 06:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0039_alter_translateperson_person_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='expire_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
