# Generated by Django 5.0.6 on 2024-08-21 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0040_notification_expire_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
