# Generated by Django 5.0.6 on 2024-08-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0041_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='notification_images/')),
                ('expire_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
