# Generated by Django 5.0.6 on 2024-08-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0042_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
