# Generated by Django 5.0.6 on 2024-08-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0043_alter_notification_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='expire_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='image_url',
            field=models.FileField(blank=True, null=True, upload_to='notification_images/'),
        ),
    ]
