# Generated by Django 5.0.6 on 2024-08-23 06:48

import django.db.models.deletion
import notifications.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parivar", "0044_alter_notification_expire_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="image_url",
        ),
        migrations.CreateModel(
            name="NotificationImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_url",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=notifications.storages.NotificationImageS3Storage(),
                        upload_to="notification_images/",
                    ),
                ),
                (
                    "notification_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parivar.notification",
                    ),
                ),
            ],
        ),
    ]
