# Generated by Django 5.0.6 on 2024-08-26 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0045_remove_notification_image_url_notificationimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonPlayerId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parivar.person')),
            ],
        ),
    ]
