# Generated by Django 5.0.6 on 2024-08-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0046_personplayerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personplayerid',
            name='player_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
