# Generated by Django 5.0.6 on 2024-08-28 11:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0047_alter_personplayerid_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='created_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parivar.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='filter',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personplayerid',
            name='platform',
            field=models.CharField(blank=True, choices=[('Android', 'Android'), ('Ios', 'Ios')], default='Android', max_length=100, null=True),
        ),
    ]
