# Generated by Django 5.0.6 on 2024-09-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0048_notification_created_at_notification_created_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_show_left_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='start_date',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='emoji',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='expire_date',
            field=models.CharField(max_length=256),
        ),
    ]
