# Generated by Django 5.0.6 on 2024-09-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0049_notification_is_show_left_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='expire_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
