# Generated by Django 5.0.6 on 2024-09-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0050_alter_notification_expire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_show_ad_lable',
            field=models.BooleanField(default=False),
        ),
    ]
