# Generated by Django 5.0.6 on 2024-09-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0051_notification_is_show_ad_lable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personplayerid',
            name='player_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
