# Generated by Django 5.0.6 on 2024-09-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0053_alter_personplayerid_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_super_uper',
            field=models.BooleanField(default=False),
        ),
    ]
