# Generated by Django 5.0.6 on 2024-09-09 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0054_person_is_super_uper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='image_url',
            new_name='images',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title',
        ),
        migrations.AddField(
            model_name='banner',
            name='created_person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parivar.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
