# Generated by Django 5.0.6 on 2024-09-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0055_rename_date_banner_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_ad_lable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parentchildrelation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='translateperson',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
