# Generated by Django 5.0.6 on 2024-09-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0056_banner_is_ad_lable_parentchildrelation_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_random_banner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
