# Generated by Django 5.0.6 on 2024-09-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0057_randombanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='redirect_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
