# Generated by Django 5.0.6 on 2024-09-16 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0058_notification_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PersonUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_history', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_updates', to='parivar.person')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_logs', to='parivar.person')),
            ],
        ),
    ]
