# Generated by Django 5.0.6 on 2024-09-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0059_person_deleted_at_personupdatelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_reminder_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_event',
            field=models.BooleanField(default=False),
        ),
    ]
