# Generated by Django 5.0.6 on 2024-10-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0060_notification_event_reminder_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_show_old_contact',
            field=models.BooleanField(default=True),
        ),
    ]
