# Generated by Django 5.0.6 on 2024-12-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0061_person_is_show_old_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationimage',
            name='notification_id',
        ),
        migrations.RemoveField(
            model_name='personplayerid',
            name='person',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='NotificationImage',
        ),
        migrations.DeleteModel(
            name='PersonPlayerId',
        ),
    ]
