# Generated by Django 5.0.6 on 2025-12-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0062_remove_notificationimage_notification_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='update_field_message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
