# Generated by Django 5.0.6 on 2026-02-06 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0063_person_update_field_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('guj_name', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='parivar.state')),
            ],
            options={
                'unique_together': {('name', 'state')},
            },
        ),
        migrations.AddField(
            model_name='person',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parivar.district'),
        ),
        migrations.CreateModel(
            name='Taluka',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('guj_name', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talukas', to='parivar.district')),
            ],
            options={
                'unique_together': {('name', 'district')},
            },
        ),
        migrations.AddField(
            model_name='person',
            name='taluka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parivar.taluka'),
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('guj_name', models.CharField(blank=True, max_length=255, null=True)),
                ('taluka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='parivar.taluka')),
            ],
            options={
                'unique_together': {('name', 'taluka')},
            },
        ),
        migrations.AddField(
            model_name='person',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parivar.village'),
        ),
    ]
