# Generated by Django 5.0.6 on 2026-02-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0064_district_person_district_taluka_person_taluka_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taluka',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='village',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
