# Generated by Django 5.0.6 on 2026-02-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0065_district_is_active_taluka_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='referral_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
