# Generated by Django 5.0.6 on 2026-02-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0066_village_referral_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('name',)},
        ),
        migrations.AddField(
            model_name='person',
            name='country_mobile_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_out_of_country',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='district',
            name='state',
        ),
    ]
