# Generated by Django 5.0.6 on 2026-02-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0067_alter_district_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='country_mobile_number',
            new_name='international_mobile_number',
        ),
        migrations.AddField(
            model_name='person',
            name='guj_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='guj_middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
