# Generated by Django 5.0.6 on 2026-02-13 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0068_rename_country_mobile_number_person_international_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DemoPerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number1', models.CharField(blank=True, max_length=12, null=True)),
                ('mobile_number2', models.CharField(blank=True, max_length=12, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('out_of_address', models.CharField(blank=True, max_length=500, null=True)),
                ('out_of_mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('is_out_of_country', models.BooleanField(default=False)),
                ('international_mobile_number', models.CharField(blank=True, max_length=50, null=True)),
                ('guj_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guj_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('child_flag', models.BooleanField(default=False)),
                ('flag_show', models.BooleanField(default=False)),
                ('is_demo', models.BooleanField(default=True)),
                ('profile', models.ImageField(blank=True, max_length=512, null=True, upload_to='profiles/')),
                ('thumb_profile', models.ImageField(blank=True, max_length=512, null=True, upload_to='compress_img/')),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_same_as_father_address', models.BooleanField(default=False)),
                ('is_same_as_son_address', models.BooleanField(default=False)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('is_super_uper', models.BooleanField(default=False)),
                ('is_show_old_contact', models.BooleanField(default=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('platform', models.CharField(blank=True, default='postman', max_length=30, null=True)),
                ('emoji', models.CharField(blank=True, max_length=512, null=True)),
                ('is_registered_directly', models.BooleanField(default=False)),
                ('update_field_message', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_by', models.IntegerField(blank=True, default=0, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parivar.city')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parivar.district')),
                ('out_of_country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parivar.country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parivar.state')),
                ('surname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parivar.surname')),
                ('taluka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parivar.taluka')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parivar.village')),
            ],
            options={
                'unique_together': {('first_name', 'middle_name', 'date_of_birth', 'surname', 'mobile_number1', 'mobile_number2')},
            },
        ),
        migrations.CreateModel(
            name='DemoParentChildRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_child_relations', to='parivar.demoperson')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parivar.demoperson')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_parent_relations', to='parivar.demoperson')),
            ],
        ),
    ]
