# Generated by Django 5.0.6 on 2026-02-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0069_person_is_demo_demoperson_demoparentchildrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoSurname',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, unique=True)),
                ('top_member', models.CharField(blank=True, default='', max_length=100)),
                ('guj_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fix_order', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
