# Generated by Django 5.0.6 on 2026-02-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0070_demosurname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='village',
            name='referral_code',
        ),
        migrations.CreateModel(
            name='Samaj',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='English samaj name', max_length=100)),
                ('guj_name', models.CharField(blank=True, help_text='Gujarati samaj name', max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, max_length=512, null=True, upload_to='samaj_logos/')),
                ('referral_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('villages', models.ManyToManyField(blank=True, related_name='samaj_list', to='parivar.village')),
            ],
            options={
                'verbose_name_plural': 'Samaj',
            },
        ),
    ]
