# Generated by Django 5.0.6 on 2026-02-16 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0071_remove_village_referral_code_samaj'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='samaj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='parivar.samaj'),
        ),
    ]
