# Generated by Django 5.0.6 on 2026-02-16 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parivar', '0072_person_is_premium_person_samaj'),
    ]

    operations = [
        migrations.AddField(
            model_name='samaj',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samaj_list', to='parivar.village'),
        ),
        migrations.RemoveField(
            model_name='samaj',
            name='villages',
        ),
        migrations.AlterUniqueTogether(
            name='samaj',
            unique_together={('name', 'village')},
        ),
    ]
