# Generated by Django 5.0.6 on 2026-02-10 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parivar', '0065_district_is_active_taluka_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Category name (English)', max_length=100, unique=True)),
                ('guj_name', models.CharField(blank=True, help_text='Category name (Gujarati)', max_length=100, null=True)),
                ('icon', models.CharField(blank=True, help_text="Icon key for frontend (e.g., 'food', 'retail')", max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable category')),
                ('display_order', models.IntegerField(default=0, help_text='Sort order for display')),
            ],
            options={
                'verbose_name_plural': 'Business Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SearchIntent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(help_text='Base keyword (normalized)', max_length=100, unique=True)),
                ('related_terms', models.TextField(help_text='Comma-separated synonyms and related terms')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['keyword'],
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Business name (English default)', max_length=255)),
                ('description', models.TextField(help_text='Business description')),
                ('logo', models.ImageField(blank=True, help_text='Business logo/icon', null=True, upload_to='business_logos/%Y/%m/')),
                ('keywords', models.TextField(help_text='Normalized keywords (comma-separated, lowercase)')),
                ('contact_mobile', models.CharField(blank=True, help_text='Primary contact number', max_length=15, null=True)),
                ('contact_whatsapp', models.CharField(blank=True, help_text='WhatsApp number (can be same as mobile)', max_length=15, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Admin verified business')),
                ('is_active', models.BooleanField(default=True, help_text='Visible to users')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('profile_score', models.IntegerField(default=0, help_text='Completeness score (0-100)')),
                ('views_count', models.IntegerField(default=0, help_text='Total profile views')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='parivar.district')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='parivar.state')),
                ('taluka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='parivar.taluka')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='parivar.village')),
                ('category', models.ForeignKey(help_text='Business type/category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='business.businesscategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Original image', upload_to='business_images/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Auto-generated thumbnail (300x300)', null=True, upload_to='business_thumbnails/%Y/%m/')),
                ('is_primary', models.BooleanField(default=False, help_text='Cover/featured image')),
                ('display_order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='business.business')),
            ],
            options={
                'ordering': ['-is_primary', 'display_order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Owner name (for external owners or display override)', max_length=255)),
                ('mobile', models.CharField(help_text='Owner mobile number', max_length=15)),
                ('role', models.CharField(choices=[('PRIMARY', 'Primary Owner'), ('PARTNER', 'Partner')], default='PARTNER', help_text='Ownership role', max_length=20)),
                ('owner_type', models.CharField(choices=[('REGISTERED', 'Registered User'), ('EXTERNAL', 'External Owner')], help_text='Type of owner', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Active ownership status')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners_set', to='business.business')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_businesses', to='parivar.person')),
            ],
            options={
                'verbose_name': 'Business Owner',
                'verbose_name_plural': 'Business Owners',
                'ordering': ['-role', 'added_at'],
                'unique_together': {('business', 'person', 'mobile')},
            },
        ),
        migrations.AddField(
            model_name='business',
            name='owners',
            field=models.ManyToManyField(help_text='Business owners/partners', related_name='businesses', through='business.BusinessOwner', to='parivar.person'),
        ),
        migrations.CreateModel(
            name='BusinessSearchHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(help_text='Raw search term as entered by user', max_length=255)),
                ('normalized_keyword', models.CharField(help_text='Cleaned/normalized keyword (lowercase, trimmed)', max_length=255)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('last_notified_at', models.DateTimeField(blank=True, help_text='Last time user was notified about this keyword', null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_search_history', to='parivar.person')),
            ],
            options={
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchInterest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=255)),
                ('search_count', models.IntegerField(default=1, help_text='Total number of searches')),
                ('last_searched_at', models.DateTimeField(auto_now=True)),
                ('village', models.ForeignKey(blank=True, help_text='Village scope (null = global)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_interests', to='parivar.village')),
            ],
            options={
                'ordering': ['-search_count', '-last_searched_at'],
            },
        ),
        migrations.CreateModel(
            name='TranslateBusiness',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('en', 'English'), ('guj', 'Gujarati')], default='guj', max_length=3)),
                ('title', models.CharField(help_text='Translated business name', max_length=255)),
                ('description', models.TextField(help_text='Translated description')),
                ('is_deleted', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='business.business')),
            ],
            options={
                'verbose_name_plural': 'Business Translations',
            },
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['category', 'is_active'], name='business_bu_categor_009946_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['village', 'is_active'], name='business_bu_village_9d6c31_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_verified', 'is_active'], name='business_bu_is_veri_e7b2c9_idx'),
        ),
        migrations.AddIndex(
            model_name='businesssearchhistory',
            index=models.Index(fields=['person', '-searched_at'], name='business_bu_person__a0db1f_idx'),
        ),
        migrations.AddIndex(
            model_name='businesssearchhistory',
            index=models.Index(fields=['normalized_keyword'], name='business_bu_normali_bf18de_idx'),
        ),
        migrations.AddIndex(
            model_name='searchinterest',
            index=models.Index(fields=['village', '-search_count'], name='business_se_village_af6057_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='searchinterest',
            unique_together={('keyword', 'village')},
        ),
        migrations.AlterUniqueTogether(
            name='translatebusiness',
            unique_together={('business', 'language')},
        ),
    ]
