# Generated by Django 5.0.6 on 2026-02-11 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Subcategory name (English)', max_length=100)),
                ('guj_name', models.CharField(blank=True, help_text='Subcategory name (Gujarati)', max_length=100, null=True)),
                ('icon', models.CharField(blank=True, help_text='Icon key for frontend', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable subcategory')),
                ('display_order', models.IntegerField(default=0, help_text='Sort order within category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Parent category', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='business.businesscategory')),
            ],
            options={
                'verbose_name_plural': 'Business Subcategories',
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='business',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Business subcategory (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='business.businesssubcategory'),
        ),
        migrations.AddIndex(
            model_name='businesssubcategory',
            index=models.Index(fields=['category', 'is_active'], name='business_bu_categor_ba14f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='businesssubcategory',
            unique_together={('category', 'name')},
        ),
    ]
