# Generated by Django 5.0.6 on 2026-02-11 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoBusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('guj_name', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemoSurname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('guj_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemoLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('guj_name', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(choices=[('STATE', 'State'), ('DISTRICT', 'District'), ('TALUKA', 'Taluka'), ('VILLAGE', 'Village')], max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='demo.demolocation')),
            ],
        ),
        migrations.CreateModel(
            name='DemoPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='demo/profiles/')),
                ('is_admin', models.BooleanField(default=False)),
                ('guj_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guj_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.ForeignKey(limit_choices_to={'level': 'VILLAGE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.demolocation')),
                ('surname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.demosurname')),
            ],
        ),
        migrations.CreateModel(
            name='DemoBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('guj_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('contact_mobile', models.CharField(max_length=15)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.demobusinesscategory')),
                ('village', models.ForeignKey(limit_choices_to={'level': 'VILLAGE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.demolocation')),
                ('owners', models.ManyToManyField(related_name='demo_businesses', to='demo.demoperson')),
            ],
        ),
        migrations.CreateModel(
            name='DemoNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('is_event', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('village_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.demolocation')),
                ('surname_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.demosurname')),
            ],
        ),
        migrations.CreateModel(
            name='DemoParentChildRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to='demo.demoperson')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_relations', to='demo.demoperson')),
            ],
            options={
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
