# Generated by Django 5.0.6 on 2026-02-11 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_demosurname_top_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoBusinessSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('guj_name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='demo.demobusinesscategory')),
            ],
        ),
        migrations.AddField(
            model_name='demobusiness',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.demobusinesssubcategory'),
        ),
    ]
