# Generated by Django 5.0.6 on 2026-02-11 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_demobusinesssubcategory_demobusiness_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('guj_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemoState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('guj_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='demoperson',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.demodistrict'),
        ),
        migrations.AddField(
            model_name='demodistrict',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='demo.demostate'),
        ),
        migrations.AddField(
            model_name='demoperson',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.demostate'),
        ),
        migrations.CreateModel(
            name='DemoTaluka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('guj_name', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talukas', to='demo.demodistrict')),
            ],
        ),
        migrations.AddField(
            model_name='demoperson',
            name='taluka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.demotaluka'),
        ),
        migrations.CreateModel(
            name='DemoVillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('guj_name', models.CharField(blank=True, max_length=100, null=True)),
                ('taluka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='demo.demotaluka')),
            ],
        ),
        migrations.AlterField(
            model_name='demobusiness',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.demovillage'),
        ),
        migrations.AlterField(
            model_name='demonotification',
            name='village_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.demovillage'),
        ),
        migrations.AlterField(
            model_name='demoperson',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.demovillage'),
        ),
        migrations.DeleteModel(
            name='DemoLocation',
        ),
    ]
