# Generated by Django 5.0.6 on 2026-02-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_demodistrict_demostate_demoperson_district_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demoperson',
            old_name='mobile_number',
            new_name='mobile_number1',
        ),
        migrations.AddField(
            model_name='demoperson',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demoperson',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demoperson',
            name='flag_show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='demoperson',
            name='is_registered_directly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demoperson',
            name='is_super_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demoperson',
            name='mobile_number2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='demoperson',
            name='out_of_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='demoperson',
            name='platform',
            field=models.CharField(blank=True, default='postman', max_length=30, null=True),
        ),
    ]
