# Generated by Django 5.0.6 on 2026-02-11 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_rename_mobile_number_demoperson_mobile_number1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('guj_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='demoperson',
            name='country_mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='demoperson',
            name='is_out_of_country',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demoperson',
            name='out_of_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.democountry'),
        ),
    ]
