# Generated by Django 5.0.6 on 2026-02-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_democountry_demoperson_country_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demoperson',
            name='country_mobile_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='demoperson',
            name='mobile_number1',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='demoperson',
            name='mobile_number2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
