# Generated by Django 5.0.6 on 2024-12-12 12:23

import django.db.models.deletion
import notifications.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parivar', '0062_remove_notificationimage_notification_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('redirect_url', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
                ('is_event', models.BooleanField(default=False)),
                ('event_reminder_date', models.DateTimeField(blank=True, null=True)),
                ('created_user', models.CharField(blank=True, max_length=255, null=True)),
                ('filter', models.JSONField(blank=True, null=True)),
                ('is_show_left_time', models.BooleanField(default=False)),
                ('is_show_ad_lable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('to_person', models.ManyToManyField(blank=True, related_name='notifications_persons', to='parivar.person')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.FileField(blank=True, null=True, storage=notifications.storages.NotificationImageS3Storage(), upload_to='notification_images/')),
                ('notification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notification')),
            ],
        ),
        migrations.CreateModel(
            name='PersonPlayerId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('platform', models.CharField(blank=True, choices=[('Android', 'Android'), ('Ios', 'Ios')], default='Android', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parivar.person')),
            ],
        ),
    ]
