# Generated by Django 5.0.6 on 2024-12-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personplayerid',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
